install(
    TARGETS ${ADT_TARGET}
    RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX}/bin
    LIBRARY DESTINATION ${CMAKE_INSTALL_PREFIX}/lib
    ARCHIVE DESTINATION ${CMAKE_INSTALL_PREFIX}/lib
)

# Don't install pkg-config file

if(INSTALL_HEADERS)
    set(INSTALL_INCLUDEDIR ${CMAKE_INSTALL_PREFIX}/include)

    install(
        FILES ${ADT_HEADER} ${ADT_C_HEADER}
        DESTINATION ${INSTALL_INCLUDEDIR}
    )

    install(
        FILES ${ADT_SUBHEADERS}
        DESTINATION ${INSTALL_INCLUDEDIR}/adt
    )

endif()
