set(GTKMM_VERSION_MAJOR  3)
set(GTKMM_VERSION_MINOR  22)
set(GTKMM_VERSION_MICRO  2)

set(GDKMM_VERSION_MAJOR  ${GTKMM_VERSION_MAJOR})
set(GDKMM_VERSION_MINOR  ${GTKMM_VERSION_MINOR})
set(GDKMM_VERSION_MICRO  ${GTKMM_VERSION_MICRO})

set(GTKMM_VERSION ${GTKMM_VERSION_MAJOR}.${GTKMM_VERSION_MINOR}.${GTKMM_VERSION_MICRO})

